configuration:
  any:
    - .devcontainer/*
    - .editorconfig
    - .gitattributes
    - .gitignore
    - .github/*yml
    - .trunk/configs
    - .vscode/*
    - DogApparel/.trunk/trunk.yaml
documentation:
  any:
    - CHANGELOG.TXT
    - CHANGELOG.md
    - CODE_OF_CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE
    - README.md
    - SUPPORT.md
    - Wiki.md
github:
  any:
    - .github/*
    - .github/workflows/*
github_actions:
  any:
    - .github/workflows/*.yaml
    - .github/workflows/*.yml
images:
  any:
    - 'public/**/*.{ico,svg,jpg,jpeg,png,gif}'
    - 'Textures/DogApparel/Things/Pawn/Animal/Body/*png'
    - 'Textures/DogApparel/Things/Pawn/Animal/Head/*png'
    - 'Textures/DogApparel/Things/Pawn/Humanlike/Body/*png'
    - 'Textures/DogApparel/Things/Pawn/Humanlike/Head/*png'
policy:
  any:
    - .github/ISSUE_TEMPLATE/*
    - .github/PULL_TEMPLATE/*
source:
  any:
    - src/DogApparel
    - src/docs/DogApparel
XML:
  any:
    - DogApparel/1.4/Defs/*.xml
    - DogApparel/About/About.xml
    - DogApparel/LoadFolders.xml
    - DogApparel/patches/Defs/*.xml
