source:
any:
 - src/DogApparel
 - src/docs/DogApparel
documentation:
any:
 - README.md
 - CHANGELOG.md
 - CHANGELOG.TXT
 - CODE_OF_CONDUCT.md
 - CONTRIBUTING.md
 - LICENSE
 - SUPPORT.md
 - Wiki.md
XML:
any:
 - DogApparel/1.4/Defs/*.xml
 - DogApparel/patches/Defs/*.xml
 - DogApparel/About/About.xml
 - DogApparel/LoadFolders.xml
configuration:
any:
 - .github/*yml
 - .gitignore
 - .gitattributes
 - .vscode/*
 - .devcontainer/*
 - .editorconfig
 - yamllint.yml
 - .trunk/configs
 - DogApparel/.trunk/trunk.yaml
images:
any:
- 'public/**/*.{ico,svg,jpg,jpeg,png,gif}'
- Textures/DogApparel/Things/Pawn/Animal/Body/*png
- Textures/DogApparel/Things/Pawn/Animal/Head/*png
- Textures/DogApparel/Things/Pawn/Humanlike/Body/*png
- Textures/DogApparel/Things/Pawn/Humanlike/Head/*png
github:
any:
- .github/*
- .github/workflows/*
github_actions:
any:
- .github/workflows/*.yml
- .github/workflows/*.yaml
policy:
any:
- .github/ISSUE_TEMPLATE/*
- .github/PULL_TEMPLATE/*
- LICENSE
- SECURITY.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- SUPPORT.md
vscode:
- .vscode/*
