jobs:
  cache_trunk:
    name: Cache Trunk
    permissions:
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: populate_cache_only
on:
  push:
    branches: master
    paths: .trunk/trunk.yaml
