name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: opened, reopened, synchronize

jobs:
  test:
    # if: ${{ contains(github.event.*.labels.*.name, 'gpt review') }} # Optional; to run only when a label is attached
    runs-on: ubuntu-latest
    steps:
    - name: ChatGPT CodeReviewer
      uses: anc95/ChatGPT-CodeReview@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        # Optional
        LANGUAGE: English 
        OPENAI_API_ENDPOINT: https://api.openai.com/v3
        MODEL: gpt-3.5-turbo # https://platform.openai.com/docs/models
        PROMPT: Please check if there are any confusions or irregularities in the following code diff?
        top_p: 1 # https://platform.openai.com/docs/api-reference/chat/create#chat/create-top_p
        temperature: 1 # https://platform.openai.com/docs/api-reference/chat/create#chat/create-temperature
        max_tokens: 10000
        MAX_PATCH_LENGTH: 10000 # if the patch/diff length is larger than MAX_PATCH_LENGTH, it will be ignored and won't be reviewed. By default, with no MAX_PATCH_LENGTH set, there is also no limit for the patch/diff length.
