name: Pull Request Labeler
on:
  pull_request_target:
  workflow_dispatch:
  schedule:
  - cron: "0 1 * * 1"

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        repository: Chunnyluny-RimWorld-Modding/DogApparel

    - name: Label Pull Request
      id: label-the-PR
      uses: actions/labeler@v4.3.0
      with:
        repo-token: "${{ secrets.LABELER_ACTION }}"
        dot: true
        sync-labels: true
