name: pmd
on:
  push:
    branches: master
  pull_request:
    branches: master
  schedule:
    - cron: "0 */2 * * *"

permissions:
  contents: read

jobs:
  pmd-code-scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: "11"
    - uses: pmd/pmd-github-action@v1
      with:
        rulesets: ruleset.xml
        analyzeModifiedFilesOnly: false
    - name: Upload SARIF file
    - uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: pmd-report.sarif
